import { UserRole } from '@core/models/Enums/UserRole';
import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'Principal',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  {
    path: 'dashboard',
    title: 'Dashboard',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  {
    path: 'branch/branch-list',
    title: 'Sucursales',
    iconType: 'material-icons-outlined',
    icon: 'location_city',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [UserRole.Admin, UserRole.Supervisor_Sucursales],
    submenu: [],
  },

  {
    path: 'patient/patient-list',
    title: 'Pacientes',
    iconType: 'material-icons-outlined',
    icon: 'account_box',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [UserRole.Admin, UserRole.Medico],
    submenu: [],
  },

  {
    path: 'prescription/prescription-list',
    title: 'Recetas',
    iconType: 'material-icons-outlined',
    icon: 'assignment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [UserRole.Admin, UserRole.Medico, UserRole.Paciente],
    submenu: [],
  },

  {
    path: 'doctor/doctor-list',
    title: 'Medicos',
    iconType: 'material-icons-outlined',
    icon: 'medication',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Empleado_Farmacia,
      UserRole.Responsable_Farmacia,
      UserRole.Supervisor_Sucursales,
    ],
    submenu: [],
  },

  /*
  {
    path: '',
    title: 'Soporte',
    iconType: 'material-icons-outlined',
    icon: 'support_agent',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  */

  {
    path: '',
    title: 'Administración',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Responsable_Farmacia,
      UserRole.Supervisor_Sucursales,
    ],
    submenu: [],
  },

  {
    path: 'admin/user-list',
    title: 'Usuarios',
    iconType: 'material-icons-outlined',
    icon: 'group',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Responsable_Farmacia,
      UserRole.Supervisor_Sucursales,
    ],
    submenu: [],
  },

  {
    path: '',
    title: 'Perfil',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  {
    path: 'user-profile',
    title: 'Perfil',
    iconType: 'material-icons-outlined',
    icon: 'account_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
];
