import {UserRole} from '@core/models/Enums/UserRole';
import {RouteInfo} from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'Principal',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: 'dashboard',
    title: 'Inicio',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: 'patient/patient-list',
    title: 'Pacientes',
    iconType: 'material-icons-outlined',
    icon: 'account_box',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Medico,
    ],
    submenu: [],
  },
  {
    path: 'prescription/prescription-list',
    title: 'Recetas',
    iconType: 'material-icons-outlined',
    icon: 'assignment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [UserRole.Admin, UserRole.Medico],
    submenu: [
      // {
      //   path: 'prescription/prescription-list',
      //   title: 'Lista',
      //   iconType: 'material-icons-outlined',
      //   icon: 'description',
      //   class: '',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: ['All'],
      //   submenu: [],
      // },
      // {
      //   path: 'prescription/prescription-supply',
      //   title: 'Surtir',
      //   iconType: 'material-icons-outlined',
      //   icon: 'done_outline',
      //   class: '',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: ['All'],
      //   submenu: [],
      // },
    ],
  },
  {
    path: 'prescription/prescription-supply',
    title: 'Surtir Receta',
    iconType: 'material-icons-outlined',
    icon: 'done_outline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Empleado_Farmacia, UserRole.Supervisor_Sucursales, UserRole.Responsable_Farmacia,
    ],
    submenu: [],
  },
  {
    path: '',
    title: 'Administración',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin, UserRole.Supervisor_Sucursales,
      UserRole.Responsable_Farmacia
    ],
    submenu: [],
  },
  {
    path: 'admin/user-list',
    title: 'Personal',
    iconType: 'material-icons-outlined',
    icon: 'group',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin, UserRole.Supervisor_Sucursales,
      UserRole.Responsable_Farmacia
    ],
    submenu: [],
  },
  {
    path: 'doctor/doctor-list',
    title: 'Medicos',
    iconType: 'material-icons-outlined',
    icon: 'medication',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Supervisor_Sucursales, UserRole.Responsable_Farmacia
    ],
    submenu: [],
  },
  {
    path: 'branch/branch-list',
    title: 'Sucursales',
    iconType: 'material-icons-outlined',
    icon: 'location_city',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Supervisor_Sucursales
    ],
    submenu: [],
  },
  // {
  //   path: 'reports/reports-list',
  //   title: 'Reportes',
  //   iconType: 'fas fa-chart-bar',
  //   icon: '',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['All'],
  //   submenu: [],
  // },
  {
    path: '',
    title: 'Configuracion',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Medico,
    ],
    submenu: [],
  },
  {
    path: 'catalogs/catalogs-list',
    title: 'Catalogos',
    iconType: 'material-icons-outlined',
    icon: 'people_outline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin,
      UserRole.Medico,
    ],
    submenu: [],
  },
  {
    path: 'catalogs/catalogs-list-v2',
    title: 'Catalogos V2',
    iconType: 'material-icons-outlined',
    icon: 'people_outline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [
      UserRole.Admin
    ],
    submenu: [],
  },
  {
    path: '',
    title: 'Perfil',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: 'user/profile',
    title: 'Perfil',
    iconType: 'material-icons-outlined',
    icon: 'account_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
];
